// <auto-generated />
namespace DogtasticData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class DateTimePicker : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DateTimePicker));
        
        string IMigrationMetadata.Id
        {
            get { return "201905201927590_DateTimePicker"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
